[theme]
base = "light"
primaryColor = "#084F86"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F6F8FA"
textColor = "#15283A"
font = "sans serif"

[server]
headless = true
maxUploadSize = 1000

[client]
toolbarMode = "minimal"

[browser]
gatherUsageStats = false
